name: backstage-infrastructure
services:
  postgres:
    image: postgres:16
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: P@ssword0123
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/raymond.boles/docker/volumes/postgres/
